#Pushing one of the most stable and light-weight versions
FROM nginx:alpine

#Removing standard configuration
RUN rm /etc/nginx/conf.d/default.conf

#Copying NGINX configuration to container
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

#Copying the frontend to the NGINX container
COPY ./project/frameworks_and_drivers/frontend /usr/share/nginx/html

#Starting NGINX server when we run the container
CMD ["nginx", "-g", "daemon off;"]