#Allocating two workers to process the requests
worker_processes  2;

events {
    #Maximum of connections per worker will be 1024
    worker_connections  1024;
}

http {
    
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        off;
    keepalive_timeout  65;

    server {

        listen       80;
        server_name  localhost;

        location / {
            root "/usr/share/nginx/html";
            index index.html index.htm;
            try_files $uri $uri/ =404;
        }

        location /api/ {
            proxy_pass http://api_node:3000/;
        }

    }

}