FROM node:22-alpine

WORKDIR /api

COPY ./web_api/package-lock.json package-lock.json
COPY ./web_api/package.json package.js

RUN npm install

COPY ./web_api/api.js ./web_api/api.js
COPY ./project/frameworks_and_drivers/api_for_web ./project/frameworks_and_drivers/api_for_web
COPY ./project/frameworks_and_drivers/databases ./project/frameworks_and_drivers/databases
COPY ./.env ./.env

CMD ["npm", "run", "dev"]